// <auto-generated />
namespace Despesa.Lite.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dois : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dois));
        
        string IMigrationMetadata.Id
        {
            get { return "201702111643527_dois"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
